version: '3'
services:
  web:
    container_name: web
    image: nginx:1.13.5-alpine
    ports:
      - "80:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ../src:/var/www/html
    depends_on:
      - php
  php:
    container_name: php
    image: php:7.3.0-fpm-alpine3.8
    volumes:
      - ./php:/usr/local/etc/php-fpm.d/default.conf
      - ../src:/var/www/html

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: